[package]
name = "d06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_set = "0.1.3"
common = { path = "../common" }
range-ext = "0.1.3"
