# [package]
# name = "aoc-2020"
# version = "0.1.0"
# edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "d01",
    "d02",
    "d03",
    "d04",
]
